baseURL = "http://mendelg.tech/"
languageCode = "en-us"
title = "Mendel Grabski | Cloud Solution Architect"

[params]
  author = "Mendel Grabski"
  github = "https://github.com/grabskimm"
  linkedin = "https://www.linkedin.com/in/mendel-grabski/"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  articles = "/articles/:slug/"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "About"
    url = "#about"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "#experience"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "#projects"
    weight = 3
